export type ProductType = {
  id: string;
  name: string;
  category: string;
  image: string;
  sku: string;
  stock: number;
  price: string;
  status: string;
  rating: number[];
};

export const productsData = [
  {
    "id": "0o02051402",
    "name": "Tasty Metal Shirt",
    "category": "Books",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp",
    "sku": "52442",
    "stock": 0,
    "price": "410.00",
    "status": "Pending",
    "rating": [4, 5, 3, 2],
    "description": "A stylish and durable shirt, perfect for casual wear. Crafted with high-quality materials for long-lasting comfort.",
    "seller_info": {
      "name": "John Doe",
      "contact": "john.doe@example.com",
      "location": "New York, USA",
      "profile": "https://randomuser.me/api/portraits/men/1.jpg"
    },
    "created_at": "2024-12-20T10:00:00Z"
  },
  {
    "id": "0o17477064",
    "name": "Modern Cotton Gloves",
    "category": "Kids",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp",
    "sku": "98414",
    "stock": 0,
    "price": "342.00",
    "status": "Draft",
    "rating": [4, 5],
    "description": "Soft and comfortable cotton gloves designed for kids, offering excellent warmth and protection.",
    "seller_info": {
      "name": "Jane Smith",
      "contact": "jane.smith@example.com",
      "location": "San Francisco, USA",
      "profile": "https://randomuser.me/api/portraits/women/1.jpg"
    },
    "created_at": "2024-12-19T15:30:00Z"
  },
  {
    "id": "0o02374305",
    "name": "Rustic Steel Computer",
    "category": "Games",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp",
    "sku": "78192",
    "stock": 0,
    "price": "948.00",
    "status": "Draft",
    "rating": [4, 5, 2, 5, 3],
    "description": "A robust gaming computer with a sleek design and powerful features for an ultimate gaming experience.",
    "seller_info": {
      "name": "Mike Johnson",
      "contact": "mike.johnson@example.com",
      "location": "Los Angeles, USA",
      "profile": "https://randomuser.me/api/portraits/men/2.jpg"
    },
    "created_at": "2024-12-18T09:45:00Z"
  },
  {
    "id": "0o02602714",
    "name": "Licensed Concrete Cheese",
    "category": "Electronics",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/11.webp",
    "sku": "86229",
    "stock": 0,
    "price": "853.00",
    "status": "Pending",
    "rating": [3, 2],
    "description": "Unique and innovative electronic cheese slicer, perfect for modern kitchens.",
    "seller_info": {
      "name": "Emily Brown",
      "contact": "emily.brown@example.com",
      "location": "Chicago, USA",
      "profile": "https://randomuser.me/api/portraits/women/2.jpg"
    },
    "created_at": "2024-12-17T11:20:00Z"
  },
  {
    "id": "0o54011366",
    "name": "Electronic Rubber Table",
    "category": "Books",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/15.webp",
    "sku": "89762",
    "stock": 18,
    "price": "881.00",
    "status": "Publish",
    "rating": [3, 4, 5],
    "description": "A sturdy and stylish rubber table, ideal for modern homes and offices.",
    "seller_info": {
      "name": "William Davis",
      "contact": "william.davis@example.com",
      "location": "Houston, USA",
      "profile": "https://randomuser.me/api/portraits/men/3.jpg"
    },
    "created_at": "2024-12-16T08:50:00Z"
  },
  {
    "id": "0o02051402",
    "name": "Tasty Metal Shirt",
    "category": "Books",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp",
    "sku": "52442",
    "stock": 0,
    "price": "410.00",
    "status": "Pending",
    "rating": [4, 5, 3, 2],
    "description": "A stylish and durable shirt, perfect for casual wear. Crafted with high-quality materials for long-lasting comfort.",
    "seller_info": {
      "name": "John Doe",
      "contact": "john.doe@example.com",
      "location": "New York, USA",
      "profile": "https://randomuser.me/api/portraits/men/1.jpg"
    },
    "created_at": "2024-12-15T10:10:00Z"
  },
  {
    "id": "0o17477064",
    "name": "Modern Cotton Gloves",
    "category": "Kids",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp",
    "sku": "98414",
    "stock": 0,
    "price": "342.00",
    "status": "Draft",
    "rating": [4, 5],
    "description": "Soft and comfortable cotton gloves designed for kids, offering excellent warmth and protection.",
    "seller_info": {
      "name": "Jane Smith",
      "contact": "jane.smith@example.com",
      "location": "San Francisco, USA",
      "profile": "https://randomuser.me/api/portraits/women/1.jpg"
    },
    "created_at": "2024-12-14T17:25:00Z"
  },
  {
    "id": "0o02374305",
    "name": "Rustic Steel Computer",
    "category": "Games",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp",
    "sku": "78192",
    "stock": 0,
    "price": "948.00",
    "status": "Draft",
    "rating": [4, 5, 2, 5, 3],
    "description": "A robust gaming computer with a sleek design and powerful features for an ultimate gaming experience.",
    "seller_info": {
      "name": "Mike Johnson",
      "contact": "mike.johnson@example.com",
      "location": "Los Angeles, USA",
      "profile": "https://randomuser.me/api/portraits/men/2.jpg"
    },
    "created_at": "2024-12-13T12:35:00Z"
  },
  {
    "id": "0o02602714",
    "name": "Licensed Concrete Cheese",
    "category": "Electronics",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/11.webp",
    "sku": "86229",
    "stock": 0,
    "price": "853.00",
    "status": "Pending",
    "rating": [3, 2],
    "description": "Unique and innovative electronic cheese slicer, perfect for modern kitchens.",
    "seller_info": {
      "name": "Emily Brown",
      "contact": "emily.brown@example.com",
      "location": "Chicago, USA",
      "profile": "https://randomuser.me/api/portraits/women/2.jpg"
    },
    "created_at": "2024-12-12T14:40:00Z"
  },
  {
    "id": "0o54011366",
    "name": "Electronic Rubber Table",
    "category": "Books",
    "image": "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/15.webp",
    "sku": "89762",
    "stock": 18,
    "price": "881.00",
    "status": "Publish",
    "rating": [3, 4, 5],
    "description": "A sturdy and stylish rubber table, ideal for modern homes and offices.",
    "seller_info": {
      "name": "William Davis",
      "contact": "william.davis@example.com",
      "location": "Houston, USA",
      "profile": "https://randomuser.me/api/portraits/men/3.jpg"
    },
    "created_at": "2024-12-11T16:15:00Z"
  }
]


export const productsDatas = [
  {
    id: '0o02051402',
    name: 'Tasty Metal Shirt',
    category: 'Books',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp',
    sku: '52442',
    stock: 0,
    price: '410.00',
    status: 'Used',
    rating: [4, 5, 3, 2],
    description: 'A stylish and durable metal shirt perfect for all book enthusiasts.',
    dateAdded: '2024-12-10',
    seller: {
      name: 'Bookish Apparel Co.',
      contact: 'contact@bookishapparel.com',
      location: 'New York, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: false,
  },
  {
    id: '0o17477064',
    name: 'Modern Cotton Gloves',
    category: 'Kids',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp',
    sku: '98414',
    stock: 0,
    price: '342.00',
    status: 'New',
    rating: [4, 5],
    description: 'Soft and safe cotton gloves designed for children of all ages.',
    dateAdded: '2024-11-28',
    seller: {
      name: 'Kiddo Accessories',
      contact: 'support@kiddoaccessories.com',
      location: 'California, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
  {
    id: '0o02374305',
    name: 'Rustic Steel Computer',
    category: 'Games',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp',
    sku: '78192',
    stock: 0,
    price: '2200.00',
    status: 'Old',
    rating: [5, 4, 3],
    description: 'High-quality steel computer suitable for gaming enthusiasts.',
    dateAdded: '2024-12-01',
    seller: {
      name: 'Gaming Warehouse',
      contact: 'sales@gamingwarehouse.com',
      location: 'Seattle, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
{
    id: '0o02051402',
    name: 'Tasty Metal Shirt',
    category: 'Books',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp',
    sku: '52442',
    stock: 0,
    price: '410.00',
    status: 'Used',
    rating: [4, 5, 3, 2],
    description: 'A stylish and durable metal shirt perfect for all book enthusiasts.',
    dateAdded: '2024-12-10',
    seller: {
      name: 'Bookish Apparel Co.',
      contact: 'contact@bookishapparel.com',
      location: 'New York, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: false,
  },
  {
    id: '0o17477064',
    name: 'Modern Cotton Gloves',
    category: 'Kids',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp',
    sku: '98414',
    stock: 0,
    price: '342.00',
    status: 'New',
    rating: [4, 5],
    description: 'Soft and safe cotton gloves designed for children of all ages.',
    dateAdded: '2024-11-28',
    seller: {
      name: 'Kiddo Accessories',
      contact: 'support@kiddoaccessories.com',
      location: 'California, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
  {
    id: '0o02374305',
    name: 'Rustic Steel Computer',
    category: 'Games',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp',
    sku: '78192',
    stock: 0,
    price: '2200.00',
    status: 'Old',
    rating: [5, 4, 3],
    description: 'High-quality steel computer suitable for gaming enthusiasts.',
    dateAdded: '2024-12-01',
    seller: {
      name: 'Gaming Warehouse',
      contact: 'sales@gamingwarehouse.com',
      location: 'Seattle, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
{
    id: '0o02051402',
    name: 'Tasty Metal Shirt',
    category: 'Books',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp',
    sku: '52442',
    stock: 0,
    price: '410.00',
    status: 'Used',
    rating: [4, 5, 3, 2],
    description: 'A stylish and durable metal shirt perfect for all book enthusiasts.',
    dateAdded: '2024-12-10',
    seller: {
      name: 'Bookish Apparel Co.',
      contact: 'contact@bookishapparel.com',
      location: 'New York, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: false,
  },
  {
    id: '0o17477064',
    name: 'Modern Cotton Gloves',
    category: 'Kids',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp',
    sku: '98414',
    stock: 0,
    price: '342.00',
    status: 'New',
    rating: [4, 5],
    description: 'Soft and safe cotton gloves designed for children of all ages.',
    dateAdded: '2024-11-28',
    seller: {
      name: 'Kiddo Accessories',
      contact: 'support@kiddoaccessories.com',
      location: 'California, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
  {
    id: '0o02374305',
    name: 'Rustic Steel Computer',
    category: 'Games',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp',
    sku: '78192',
    stock: 0,
    price: '2200.00',
    status: 'Old',
    rating: [5, 4, 3],
    description: 'High-quality steel computer suitable for gaming enthusiasts.',
    dateAdded: '2024-12-01',
    seller: {
      name: 'Gaming Warehouse',
      contact: 'sales@gamingwarehouse.com',
      location: 'Seattle, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
{
    id: '0o02051402',
    name: 'Tasty Metal Shirt',
    category: 'Books',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp',
    sku: '52442',
    stock: 0,
    price: '410.00',
    status: 'Used',
    rating: [4, 5, 3, 2],
    description: 'A stylish and durable metal shirt perfect for all book enthusiasts.',
    dateAdded: '2024-12-10',
    seller: {
      name: 'Bookish Apparel Co.',
      contact: 'contact@bookishapparel.com',
      location: 'New York, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: false,
  },
  {
    id: '0o17477064',
    name: 'Modern Cotton Gloves',
    category: 'Kids',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp',
    sku: '98414',
    stock: 0,
    price: '342.00',
    status: 'New',
    rating: [4, 5],
    description: 'Soft and safe cotton gloves designed for children of all ages.',
    dateAdded: '2024-11-28',
    seller: {
      name: 'Kiddo Accessories',
      contact: 'support@kiddoaccessories.com',
      location: 'California, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
  {
    id: '0o02374305',
    name: 'Rustic Steel Computer',
    category: 'Games',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp',
    sku: '78192',
    stock: 0,
    price: '2200.00',
    status: 'Old',
    rating: [5, 4, 3],
    description: 'High-quality steel computer suitable for gaming enthusiasts.',
    dateAdded: '2024-12-01',
    seller: {
      name: 'Gaming Warehouse',
      contact: 'sales@gamingwarehouse.com',
      location: 'Seattle, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
{
    id: '0o02051402',
    name: 'Tasty Metal Shirt',
    category: 'Books',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp',
    sku: '52442',
    stock: 0,
    price: '410.00',
    status: 'Used',
    rating: [4, 5, 3, 2],
    description: 'A stylish and durable metal shirt perfect for all book enthusiasts.',
    dateAdded: '2024-12-10',
    seller: {
      name: 'Bookish Apparel Co.',
      contact: 'contact@bookishapparel.com',
      location: 'New York, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: false,
  },
  {
    id: '0o17477064',
    name: 'Modern Cotton Gloves',
    category: 'Kids',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp',
    sku: '98414',
    stock: 0,
    price: '342.00',
    status: 'New',
    rating: [4, 5],
    description: 'Soft and safe cotton gloves designed for children of all ages.',
    dateAdded: '2024-11-28',
    seller: {
      name: 'Kiddo Accessories',
      contact: 'support@kiddoaccessories.com',
      location: 'California, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
  {
    id: '0o02374305',
    name: 'Rustic Steel Computer',
    category: 'Games',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp',
    sku: '78192',
    stock: 0,
    price: '2200.00',
    status: 'Old',
    rating: [5, 4, 3],
    description: 'High-quality steel computer suitable for gaming enthusiasts.',
    dateAdded: '2024-12-01',
    seller: {
      name: 'Gaming Warehouse',
      contact: 'sales@gamingwarehouse.com',
      location: 'Seattle, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
{
    id: '0o02051402',
    name: 'Tasty Metal Shirt',
    category: 'Books',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp',
    sku: '52442',
    stock: 0,
    price: '410.00',
    status: 'Used',
    rating: [4, 5, 3, 2],
    description: 'A stylish and durable metal shirt perfect for all book enthusiasts.',
    dateAdded: '2024-12-10',
    seller: {
      name: 'Bookish Apparel Co.',
      contact: 'contact@bookishapparel.com',
      location: 'New York, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: false,
  },
  {
    id: '0o17477064',
    name: 'Modern Cotton Gloves',
    category: 'Kids',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp',
    sku: '98414',
    stock: 0,
    price: '342.00',
    status: 'New',
    rating: [4, 5],
    description: 'Soft and safe cotton gloves designed for children of all ages.',
    dateAdded: '2024-11-28',
    seller: {
      name: 'Kiddo Accessories',
      contact: 'support@kiddoaccessories.com',
      location: 'California, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
  {
    id: '0o02374305',
    name: 'Rustic Steel Computer',
    category: 'Games',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp',
    sku: '78192',
    stock: 0,
    price: '2200.00',
    status: 'Old',
    rating: [5, 4, 3],
    description: 'High-quality steel computer suitable for gaming enthusiasts.',
    dateAdded: '2024-12-01',
    seller: {
      name: 'Gaming Warehouse',
      contact: 'sales@gamingwarehouse.com',
      location: 'Seattle, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
{
    id: '0o02051402',
    name: 'Tasty Metal Shirt',
    category: 'Books',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp',
    sku: '52442',
    stock: 0,
    price: '410.00',
    status: 'Used',
    rating: [4, 5, 3, 2],
    description: 'A stylish and durable metal shirt perfect for all book enthusiasts.',
    dateAdded: '2024-12-10',
    seller: {
      name: 'Bookish Apparel Co.',
      contact: 'contact@bookishapparel.com',
      location: 'New York, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: false,
  },
  {
    id: '0o17477064',
    name: 'Modern Cotton Gloves',
    category: 'Kids',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp',
    sku: '98414',
    stock: 0,
    price: '342.00',
    status: 'New',
    rating: [4, 5],
    description: 'Soft and safe cotton gloves designed for children of all ages.',
    dateAdded: '2024-11-28',
    seller: {
      name: 'Kiddo Accessories',
      contact: 'support@kiddoaccessories.com',
      location: 'California, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
  {
    id: '0o02374305',
    name: 'Rustic Steel Computer',
    category: 'Games',
    image: 'https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp',
    sku: '78192',
    stock: 0,
    price: '2200.00',
    status: 'Old',
    rating: [5, 4, 3],
    description: 'High-quality steel computer suitable for gaming enthusiasts.',
    dateAdded: '2024-12-01',
    seller: {
      name: 'Gaming Warehouse',
      contact: 'sales@gamingwarehouse.com',
      location: 'Seattle, USA',
      profile: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    isVerified: true,
  },
];

